/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt



package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;

import com.google.common.base.Preconditions;
import edu.nps.moves.dis7.enumerations.*;

/**
 * Identifies the type of Entity
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a>
 */
public class EntityType extends Object implements Marshaller, Serializable
{
   /** Kind of entity uid 7 */
   protected EntityKind entityKind = EntityKind.values()[0];

   /** Domain of entity (air, surface, subsurface, space, etc.) */
   protected Domain  domain =  Domain.inst(PlatformDomain.OTHER);

   /** country to which the design of the entity is attributed uid 29 */
   protected Country country = Country.values()[0];

   /** category of entity */
   protected int category;

   /** subcategory based on category */
   protected int subCategory;

   /** specific info based on subcategory */
   protected int specific;

   /** extra is an undescribed parameter... */
   protected int extra;


/** Constructor creates and configures a new instance object */
 public EntityType()
 {
 }

  /**
   * Returns size of this serialized (marshalled) object in bytes
   * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
   * @return serialized size in bytes
   */
public synchronized int getMarshalledSize()
{
   int marshalSize = 0;

   if (entityKind != null)
       marshalSize += entityKind.getMarshalledSize();
   if (domain != null)
       marshalSize += domain.getMarshalledSize();
   if (country != null)
       marshalSize += country.getMarshalledSize();
   marshalSize += 1;  // category
   marshalSize += 1;  // subCategory
   marshalSize += 1;  // specific
   marshalSize += 1;  // extra

   return marshalSize;
}


/** Setter for {@link EntityType#entityKind}
  * @param pEntityKind new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityType setEntityKind(EntityKind pEntityKind)
{
    entityKind = pEntityKind;
    return this;
}
/** Getter for {@link EntityType#entityKind}
  * @return value of interest */
public EntityKind getEntityKind()
{
    return entityKind;
}

/** Setter for {@link EntityType#domain}
  * @param pDomain new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityType setDomain(Domain pDomain)
{
    domain = pDomain;
    return this;
}
/** Getter for {@link EntityType#domain}
  * @return value of interest */
public Domain getDomain()
{
    return domain;
}


/** Setter for {@link EntityType#country}
  * @param pCountry new value of interest
  * @return same object to permit progressive setters */
public synchronized EntityType setCountry(Country pCountry)
{
    country = pCountry;
    return this;
}
/** Getter for {@link EntityType#country}
  * @return value of interest */
public Country getCountry()
{
    return country;
}

/** Utility setter for {@link EntityType#category}
  * @param pCategory new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized EntityType setCategory(int pCategory){
    // Checking value is in value space uint8
    Preconditions.checkArgument(pCategory >= 0 && pCategory <= 255, "value outside valid value space");
    category = pCategory;
    return this;
}
/** Getter for {@link EntityType#category}
  * @return value of interest */
public int getCategory()
{
    return category;
}

/** Utility setter for {@link EntityType#subCategory}
  * @param pSubCategory new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized EntityType setSubCategory(int pSubCategory){
    // Checking value is in value space uint8
    Preconditions.checkArgument(pSubCategory >= 0 && pSubCategory <= 255, "value outside valid value space");
    subCategory = pSubCategory;
    return this;
}
/** Getter for {@link EntityType#subCategory}
  * @return value of interest */
public int getSubCategory()
{
    return subCategory;
}

/** Utility setter for {@link EntityType#specific}
  * @param pSpecific new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized EntityType setSpecific(int pSpecific){
    // Checking value is in value space uint8
    Preconditions.checkArgument(pSpecific >= 0 && pSpecific <= 255, "value outside valid value space");
    specific = pSpecific;
    return this;
}
/** Getter for {@link EntityType#specific}
  * @return value of interest */
public int getSpecific()
{
    return specific;
}

/** Utility setter for {@link EntityType#extra}
  * @param pExtra new value of interest. Value space uint8
  * @return same object to permit progressive setters */
public synchronized EntityType setExtra(int pExtra){
    // Checking value is in value space uint8
    Preconditions.checkArgument(pExtra >= 0 && pExtra <= 255, "value outside valid value space");
    extra = pExtra;
    return this;
}
/** Getter for {@link EntityType#extra}
  * @return value of interest */
public int getExtra()
{
    return extra;
}

/**
 * Serializes an object to a DataOutputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataOutputStream
 * @param dos the OutputStream
 */
public synchronized void marshal(DataOutputStream dos) throws Exception
{
    try
    {
       entityKind.marshal(dos);
       domain.marshal(dos);
       country.marshal(dos);
       dos.writeByte((byte) category);
       dos.writeByte((byte) subCategory);
       dos.writeByte((byte) specific);
       dos.writeByte((byte) extra);
    }
    catch(Exception e)
    {
      System.err.println(e);
    }
}

/**
 * Deserializes an object from a DataInputStream.
 * @throws java.lang.Exception if something goes wrong
 * @see java.io.DataInputStream
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param dis the InputStream
 * @return marshalled serialized size in bytes
 */
public synchronized int unmarshal(DataInputStream dis) throws Exception
{
    int uPosition = 0;
    try
    {
        entityKind = EntityKind.unmarshalEnum(dis);
        uPosition += entityKind.getMarshalledSize();

        // Fix to enable the use of different domain enumerations
        if (entityKind == EntityKind.MUNITION) {
            domain = Domain.inst(MunitionDomain.OTHER);
        }
        else if(entityKind == EntityKind.SUPPLY) {
            domain = Domain.inst(SupplyDomain.NOT_USED);
        }
        uPosition += domain.unmarshal(dis);
        country = Country.unmarshalEnum(dis);
        uPosition += country.getMarshalledSize();
        category = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        subCategory = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        specific = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
        extra = Byte.toUnsignedInt(dis.readByte());
        uPosition += 1;
    }
    catch(Exception e)
    {
      System.err.println(e);
    }
    return getMarshalledSize();
}

/**
 * Packs an object into the ByteBuffer.
 * @throws java.nio.BufferOverflowException if byteBuffer is too small
 * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
 * @see java.nio.ByteBuffer
 * @param byteBuffer The ByteBuffer at the position to begin writing
 * @throws Exception ByteBuffer-generated exception
 */
public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
   entityKind.marshal(byteBuffer);
   domain.marshal(byteBuffer);
   country.marshal(byteBuffer);
   byteBuffer.put((byte) category);
   byteBuffer.put((byte) subCategory);
   byteBuffer.put((byte) specific);
   byteBuffer.put((byte) extra);
}

/**
 * Unpacks a Pdu from the underlying data.
 * @throws java.nio.BufferUnderflowException if byteBuffer is too small
 * @see java.nio.ByteBuffer
 * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
 * @param byteBuffer The ByteBuffer at the position to begin reading
 * @return marshalled serialized size in bytes
 * @throws Exception ByteBuffer-generated exception
 */
public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception
{
    try
    {
        // attribute entityKind marked as not serialized
        entityKind = EntityKind.unmarshalEnum(byteBuffer);

        // Fix to enable the use of different domain enumerations
        if (entityKind == EntityKind.MUNITION) {
            domain = Domain.inst(MunitionDomain.OTHER);
        }
        else if(entityKind == EntityKind.SUPPLY) {
            domain = Domain.inst(SupplyDomain.NOT_USED);
        }
        // attribute domain marked as not serialized
        domain.unmarshal(byteBuffer);

        // attribute country marked as not serialized
        country = Country.unmarshalEnum(byteBuffer);
        // attribute category marked as not serialized
        category = Byte.toUnsignedInt(byteBuffer.get());
        // attribute subCategory marked as not serialized
        subCategory = Byte.toUnsignedInt(byteBuffer.get());
        // attribute specific marked as not serialized
        specific = Byte.toUnsignedInt(byteBuffer.get());
        // attribute extra marked as not serialized
        extra = Byte.toUnsignedInt(byteBuffer.get());
    }
    catch (java.nio.BufferUnderflowException bue)
    {
        System.err.println("*** buffer underflow error while unmarshalling " + this.getClass().getName());
    }
    return getMarshalledSize();
}

    /**
     * Unpacks a Pdu into a map from the underlying data.
     * @throws java.nio.BufferUnderflowException if byteBuffer is too small
     * @see java.nio.ByteBuffer
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     * @param byteBuffer The ByteBuffer at the position to begin reading
     * @return marshalled serialized size in bytes
     * @throws Exception ByteBuffer-generated exception
     */
    public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception {
        PduMap map = new PduMap();

        // attribute entityKind marked as not serialized
        map.put("entityKind", EntityKind.unmarshalEnum(byteBuffer));

        // attribute domain marked as not serialized
        map.put("domain", Domain.fromBufferToMap(byteBuffer));

        // attribute country marked as not serialized
        map.put("country", Country.unmarshalEnum(byteBuffer));
        // attribute category marked as not serialized
        map.put("category", Byte.toUnsignedInt(byteBuffer.get()));
        // attribute subCategory marked as not serialized
        map.put("subCategory", Byte.toUnsignedInt(byteBuffer.get()));
        // attribute specific marked as not serialized
        map.put("specific", Byte.toUnsignedInt(byteBuffer.get()));
        // attribute extra marked as not serialized
        map.put("extra", Byte.toUnsignedInt(byteBuffer.get()));

        return map;
    }

    /**
     * Packs a Pdu represented in map into the ByteBuffer.
     * @throws java.nio.BufferOverflowException if byteBuffer is too small
     * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
     * @see java.nio.ByteBuffer
     * @param byteBuffer The ByteBuffer at the position to begin writing
     * @throws Exception ByteBuffer-generated exception
     */
    public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception
    {
        ((EntityKind) map.get("entityKind")).marshal(byteBuffer);
        Domain.fromMapToBuffer((PduMap) map.get("domain"), byteBuffer);
        ((Country) map.get("country")).marshal(byteBuffer);
        byteBuffer.put(((Number) map.get("category")).byteValue());
        byteBuffer.put(((Number) map.get("subCategory")).byteValue());
        byteBuffer.put(((Number) map.get("specific")).byteValue());
        byteBuffer.put(((Number) map.get("extra")).byteValue());
    }

    /**
     * Returns size of this serialized (marshalled) object in bytes
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     * @return serialized size in bytes
     */
    public static int getMarshalledSize(PduMap map) throws Exception
    {
        int marshalSize = 0;

        marshalSize += ((EntityKind) map.get("entityKind")).getMarshalledSize();
        marshalSize += Domain.getMarshalledSize((PduMap) map.get("domain"));
        marshalSize += ((Country) map.get("country")).getMarshalledSize();
        marshalSize += 1;  // category
        marshalSize += 1;  // subCategory
        marshalSize += 1;  // specific
        marshalSize += 1;  // extra

        return marshalSize;
    }

 /*
  * Override of default equals method.  Calls equalsImpl() for content comparison.
  */
@Override
 public synchronized boolean equals(Object obj)
 {
    if(this == obj)
      return true;

    if(obj == null)
       return false;

    if(!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
        return false;

    return equalsImpl(obj);
 }

 /**
  * Compare all fields that contribute to the state, ignoring
  * transient and static fields, for <code>this</code> and the supplied object
  * @param obj the object to compare to
  * @return true if the objects are equal, false otherwise.
  */
 public synchronized boolean equalsImpl(Object obj)
 {
     final EntityType rhs = (EntityType)obj;

     if( ! (entityKind == rhs.entityKind)) return false;
     if( ! Objects.equals(domain, rhs.domain) ) return false;
     if( ! (country == rhs.country)) return false;
     if( ! (category == rhs.category)) return false;
     if( ! (subCategory == rhs.subCategory)) return false;
     if( ! (specific == rhs.specific)) return false;
     if( ! (extra == rhs.extra)) return false;
    return true;
 }

 @Override
 public synchronized String toString()
 {
    StringBuilder sb  = new StringBuilder();
    StringBuilder sb2 = new StringBuilder();
    sb.append(getClass().getSimpleName());
    sb.append(" entityKind:").append(entityKind); // writeOneToString
    sb.append(" domain:").append(domain); // writeOneToString
    sb.append(" country:").append(country); // writeOneToString
    sb.append(" category:").append(category); // writeOneToString
    sb.append(" subCategory:").append(subCategory); // writeOneToString
    sb.append(" specific:").append(specific); // writeOneToString
    sb.append(" extra:").append(extra); // writeOneToString

   return sb.toString();
 }

 @Override
 public int hashCode()
 {
     return Objects.hash(this.entityKind,
                         this.domain,
                         this.country,
                         this.category,
                         this.subCategory,
                         this.specific,
                         this.extra);
 }
} // end of EntityType
