/**
 * Copyright (c) 2008-2023, MOVES Institute, Naval Postgraduate School (NPS). All rights reserved.
 * This work is provided under a BSD-style open-source license, see project
 * <a href="https://savage.nps.edu/opendis7-java/license.html" target="_blank">license.html</a> and <a href="https://savage.nps.edu/opendis7-java/license.txt" target="_blank">license.txt</a>
 */
// header autogenerated using string template dis7javalicense.txt


package edu.nps.moves.dis7.pdus;

import java.util.*;
import java.io.*;

import edu.nps.moves.dis7.enumerations.*;

/**
 * 6.2.41, table 68
 *
 * @see <a href="https://ieeexplore.ieee.org/document/6387564" target="_blank">IEEE Std 1278.1-2012, IEEE Standard for Distributed Interactive Simulation - Application Protocols</a>
 */
public class GridData extends Object implements Serializable, Marshaller {
    /**
     * uid 246
     */
    protected GriddedDataSampleType sampleType = GriddedDataSampleType.values()[0];

    /**
     * uid 247
     */
    protected GriddedDataDataRepresentation dataRepresentation = GriddedDataDataRepresentation.values()[0];

    /**
     * type0Data is an undescribed parameter...
     */
    protected GridDataType0 type0Data = null;

    /**
     * type1Data is an undescribed parameter...
     */
    protected GridDataType1 type1Data = null;

    /**
     * type2Data is an undescribed parameter...
     */
    protected GridDataType2 type2Data = null;


    /**
     * Constructor creates and configures a new instance object
     */
    public GridData() {
    }

    /**
     * Returns size of this serialized (marshalled) object in bytes
     *
     * @return serialized size in bytes
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     */
    @Override
    public synchronized int getMarshalledSize() {
        int marshalSize = 0;

        if (sampleType != null)
            marshalSize += sampleType.getMarshalledSize();
        if (dataRepresentation != null)
            marshalSize += dataRepresentation.getMarshalledSize();
        if (type0Data != null)
            marshalSize += type0Data.getMarshalledSize();
        if (type1Data != null)
            marshalSize += type1Data.getMarshalledSize();
        if (type2Data != null)
            marshalSize += type2Data.getMarshalledSize();

        return marshalSize;
    }


    /**
     * Setter for {@link GridData#sampleType}
     *
     * @param pSampleType new value of interest
     * @return same object to permit progressive setters
     */
    public synchronized GridData setSampleType(GriddedDataSampleType pSampleType) {
        sampleType = pSampleType;
        return this;
    }

    /**
     * Getter for {@link GridData#sampleType}
     *
     * @return value of interest
     */
    public GriddedDataSampleType getSampleType() {
        return sampleType;
    }

    /**
     * Setter for {@link GridData#dataRepresentation}
     *
     * @param pDataRepresentation new value of interest
     * @return same object to permit progressive setters
     */
    public synchronized GridData setDataRepresentation(GriddedDataDataRepresentation pDataRepresentation) {
        dataRepresentation = pDataRepresentation;
        return this;
    }

    /**
     * Getter for {@link GridData#dataRepresentation}
     *
     * @return value of interest
     */
    public GriddedDataDataRepresentation getDataRepresentation() {
        return dataRepresentation;
    }

    /**
     * Setter for {@link GridData#type0Data}
     *
     * @param pType0Data new value of interest
     * @return same object to permit progressive setters
     */
    public synchronized GridData setType0Data(GridDataType0 pType0Data) {
        type0Data = pType0Data;
        type1Data = null;
        type2Data = null;
        return this;
    }

    /**
     * Getter for {@link GridData#type0Data}
     *
     * @return value of interest
     */
    public GridDataType0 getType0Data() {
        return type0Data;
    }


    /**
     * Setter for {@link GridData#type1Data}
     *
     * @param pType1Data new value of interest
     * @return same object to permit progressive setters
     */
    public synchronized GridData setType1Data(GridDataType1 pType1Data) {
        type0Data = null;
        type1Data = pType1Data;
        type2Data = null;
        return this;
    }

    /**
     * Getter for {@link GridData#type1Data}
     *
     * @return value of interest
     */
    public GridDataType1 getType1Data() {
        return type1Data;
    }


    /**
     * Setter for {@link GridData#type2Data}
     *
     * @param pType2Data new value of interest
     * @return same object to permit progressive setters
     */
    public synchronized GridData setType2Data(GridDataType2 pType2Data) {
        type0Data = null;
        type1Data = null;
        type2Data = pType2Data;
        return this;
    }

    /**
     * Getter for {@link GridData#type2Data}
     *
     * @return value of interest
     */
    public GridDataType2 getType2Data() {
        return type2Data;
    }


    /**
     * Serializes an object to a DataOutputStream.
     *
     * @param dos the OutputStream
     * @throws java.lang.Exception if something goes wrong
     * @see java.io.DataOutputStream
     */
    @Override
    public synchronized void marshal(DataOutputStream dos) throws Exception {

        {
            sampleType.marshal(dos);
            dataRepresentation.marshal(dos);
            if (type0Data != null)
                type0Data.marshal(dos);
            if (type1Data != null)
                type1Data.marshal(dos);
            if (type2Data != null)
                type2Data.marshal(dos);
        }
    }

    /**
     * Deserializes an object from a DataInputStream.
     *
     * @param dis the InputStream
     * @return marshalled serialized size in bytes
     * @throws java.lang.Exception if something goes wrong
     * @see java.io.DataInputStream
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     */
    @Override
    public synchronized int unmarshal(DataInputStream dis) throws Exception {
        int uPosition = 0;

        {
            sampleType = GriddedDataSampleType.unmarshalEnum(dis);
            uPosition += sampleType.getMarshalledSize();
            dataRepresentation = GriddedDataDataRepresentation.unmarshalEnum(dis);
            uPosition += dataRepresentation.getMarshalledSize();
            switch (dataRepresentation) {
                case TYPE_0 -> {
                    type0Data = new GridDataType0();
                    type1Data = null;
                    type2Data = null;
                    uPosition += type0Data.unmarshal(dis);
                }
                case TYPE_1 -> {
                    type0Data = null;
                    type1Data = new GridDataType1();
                    type2Data = null;
                    uPosition += type1Data.unmarshal(dis);
                }
                case TYPE_2 -> {
                    type0Data = null;
                    type1Data = null;
                    type2Data = new GridDataType2();
                    uPosition += type2Data.unmarshal(dis);
                }
            }
        }
        return getMarshalledSize();
    }

    /**
     * Packs an object into the ByteBuffer.
     *
     * @param byteBuffer The ByteBuffer at the position to begin writing
     * @throws java.nio.BufferOverflowException if byteBuffer is too small
     * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
     * @throws Exception                        ByteBuffer-generated exception
     * @see java.nio.ByteBuffer
     */
    @Override
    public synchronized void marshal(java.nio.ByteBuffer byteBuffer) throws Exception {
        sampleType.marshal(byteBuffer);
        dataRepresentation.marshal(byteBuffer);
        if (type0Data != null)
            type0Data.marshal(byteBuffer);
        if (type1Data != null)
            type1Data.marshal(byteBuffer);
        if (type2Data != null)
            type2Data.marshal(byteBuffer);
    }

    /**
     * Unpacks a Pdu from the underlying data.
     *
     * @param byteBuffer The ByteBuffer at the position to begin reading
     * @return marshalled serialized size in bytes
     * @throws java.nio.BufferUnderflowException if byteBuffer is too small
     * @throws Exception                         ByteBuffer-generated exception
     * @see java.nio.ByteBuffer
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     */
    @Override
    public synchronized int unmarshal(java.nio.ByteBuffer byteBuffer) throws Exception {
        {
            sampleType = GriddedDataSampleType.unmarshalEnum(byteBuffer);
            dataRepresentation = GriddedDataDataRepresentation.unmarshalEnum(byteBuffer);
            switch (dataRepresentation) {
                case TYPE_0 -> {
                    type0Data = new GridDataType0();
                    type1Data = null;
                    type2Data = null;
                    type0Data.unmarshal(byteBuffer);
                }
                case TYPE_1 -> {
                    type0Data = null;
                    type1Data = new GridDataType1();
                    type2Data = null;
                    type1Data.unmarshal(byteBuffer);
                }
                case TYPE_2 -> {
                    type0Data = null;
                    type1Data = null;
                    type2Data = new GridDataType2();
                    type2Data.unmarshal(byteBuffer);
                }
            }
        }
        return getMarshalledSize();
    }


    /**
     * Unpacks a Pdu into a map from the underlying data.
     *
     * @param byteBuffer The ByteBuffer at the position to begin reading
     * @return marshalled serialized size in bytes
     * @throws java.nio.BufferUnderflowException if byteBuffer is too small
     * @throws Exception                         ByteBuffer-generated exception
     * @see java.nio.ByteBuffer
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     */
    public static PduMap fromBufferToMap(java.nio.ByteBuffer byteBuffer) throws Exception {
        PduMap map;
        map = new PduMap();

        {
            map.put("sampleType", GriddedDataSampleType.unmarshalEnum(byteBuffer).getValue());
            map.put("dataRepresentation", GriddedDataDataRepresentation.unmarshalEnum(byteBuffer).getValue());
            switch ((GriddedDataDataRepresentation) map.get("dataRepresentation")) {
                case TYPE_0 -> {
                    map.put("type0Data", GridDataType0.fromBufferToMap(byteBuffer));
                }
                case TYPE_1 -> {
                    map.put("type1Data", GridDataType1.fromBufferToMap(byteBuffer));
                }
                case TYPE_2 -> {
                    map.put("type2Data", GridDataType2.fromBufferToMap(byteBuffer));
                }
            }
        }
        return map;
    }

    /**
     * Packs a Pdu represented in map into the ByteBuffer.
     *
     * @param byteBuffer The ByteBuffer at the position to begin writing
     * @throws java.nio.BufferOverflowException if byteBuffer is too small
     * @throws java.nio.ReadOnlyBufferException if byteBuffer is read only
     * @throws Exception                        ByteBuffer-generated exception
     * @see java.nio.ByteBuffer
     */
    public static void fromMapToBuffer(PduMap map, java.nio.ByteBuffer byteBuffer) throws Exception {
        GriddedDataSampleType.getEnumForValue(((Number) map.get("sampleType")).intValue()).marshal(byteBuffer);
        GriddedDataDataRepresentation.getEnumForValue(((Number) map.get("dataRepresentation")).intValue()).marshal(byteBuffer);
        if (map.containsKey("type0Data"))
            GridDataType0.fromMapToBuffer((PduMap) map.get("type0Data"), byteBuffer);
        if (map.containsKey("type1Data"))
            GridDataType1.fromMapToBuffer((PduMap) map.get("type1Data"), byteBuffer);
        if (map.containsKey("type2Data"))
            GridDataType2.fromMapToBuffer((PduMap) map.get("type2Data"), byteBuffer);
    }

    /**
     * Returns size of this serialized (marshalled) object in bytes
     *
     * @return serialized size in bytes
     * @throws Exception
     * @see <a href="https://en.wikipedia.org/wiki/Marshalling_(computer_science)" target="_blank">https://en.wikipedia.org/wiki/Marshalling_(computer_science)</a>
     */
    public static int getMarshalledSize(PduMap map) throws Exception {
        int marshalSize = 0;

        marshalSize += GriddedDataSampleType.getEnumForValue(((Number) map.get("sampleType")).intValue()).getMarshalledSize();
        marshalSize += GriddedDataDataRepresentation.getEnumForValue(((Number) map.get("dataRepresentation")).intValue()).getMarshalledSize();
        if (map.containsKey("type0Data"))
            marshalSize += GridDataType0.getMarshalledSize((PduMap) map.get("type0Data"));
        if (map.containsKey("type1Data"))
            marshalSize += GridDataType1.getMarshalledSize((PduMap) map.get("type1Data"));
        if (map.containsKey("type2Data"))
            marshalSize += GridDataType2.getMarshalledSize((PduMap) map.get("type2Data"));

        return marshalSize;
    }

    /*
     * Override of default equals method.  Calls equalsImpl() for content comparison.
     */
    @Override
    public synchronized boolean equals(Object obj) {
        if (this == obj)
            return true;

        if (obj == null)
            return false;

        if (!getClass().isAssignableFrom(obj.getClass())) //if(getClass() != obj.getClass())
            return false;

        return equalsImpl(obj);
    }

    /**
     * Compare all fields that contribute to the state, ignoring
     * transient and static fields, for <code>this</code> and the supplied object
     *
     * @param obj the object to compare to
     * @return true if the objects are equal, false otherwise.
     */
    public synchronized boolean equalsImpl(Object obj) {
        final GridData rhs = (GridData) obj;

        if (!(sampleType == rhs.sampleType)) return false;
        if (!(dataRepresentation == rhs.dataRepresentation)) return false;
        if (!Objects.equals(type0Data, rhs.type0Data)) return false;
        if (!Objects.equals(type1Data, rhs.type1Data)) return false;
        if (!Objects.equals(type2Data, rhs.type2Data)) return false;
        return true;
    }

    @Override
    public synchronized String toString() {
        StringBuilder sb = new StringBuilder();
        StringBuilder sb2 = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" sampleType:").append(sampleType); // writeOneToString
        sb.append(" dataRepresentation:").append(dataRepresentation); // writeOneToString
        sb.append(" type0Data:").append(type0Data); // writeOneToString
        sb.append(" type1Data:").append(type1Data); // writeOneToString
        sb.append(" type2Data:").append(type2Data); // writeOneToString

        return sb.toString();
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.sampleType,
                this.dataRepresentation,
                this.type0Data,
                this.type1Data,
                this.type2Data);
    }
} // end of GridData
